# Generated by Django 4.0.4 on 2022-06-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
