# Generated by Django 4.0.4 on 2022-06-19 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0002_category_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('date_time_picker', models.DateTimeField(default=datetime.datetime.now)),
                ('number_of_views', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='0:processing, 1:completed')),
                ('standard_news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_news', to='apps_nepali.standardnews')),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('date_time_picker', models.DateTimeField(default=datetime.datetime.now)),
                ('number_of_views', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='0:processing, 1:completed')),
                ('standard_news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_news', to='apps_nepali.standardnews')),
            ],
        ),
    ]
