# Generated by Django 4.0.4 on 2022-06-27 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0004_youtubelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_uploaded', models.DateField(default=datetime.datetime.now)),
                ('time_uploaded', models.TimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True, help_text='0:processing, 1:completed')),
            ],
            options={
                'db_table': 'breaking_news',
            },
        ),
    ]
