# Generated by Django 4.0.4 on 2022-07-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0005_breakingnews'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='breakingnews',
            table=None,
        ),
    ]
