# Generated by Django 4.0.2 on 2022-08-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0007_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='link',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='photo_img',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
