# Generated by Django 4.0.2 on 2022-08-21 02:06

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0010_remove_addsubtitle_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_active', models.BooleanField(default=True, help_text='0:processing, 1:completed')),
            ],
            options={
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50, null=True)),
                ('uploaded_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True, help_text='0:processing, 1:completed')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comment', to='apps_nepali.standardnews')),
            ],
            options={
                'db_table': 'NewsComment',
            },
        ),
    ]
