# Generated by Django 3.2.15 on 2022-08-25 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0011_aboutus_newscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnews',
            name='date_time_picker',
        ),
        migrations.AddField(
            model_name='standardnews',
            name='date_time_picker',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
