# Generated by Django 3.2.15 on 2022-08-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0013_auto_20220825_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardnews',
            name='date_time_picker',
        ),
    ]
