# Generated by Django 3.2.15 on 2022-08-25 10:00

import apps_nepali.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0015_auto_20220825_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='standard_news',
            field=models.OneToOneField(default=apps_nepali.models.StandardNews, on_delete=django.db.models.deletion.CASCADE, related_name='latest_news', to='apps_nepali.standardnews'),
        ),
        migrations.AddField(
            model_name='mainnews',
            name='standard_news',
            field=models.OneToOneField(default=apps_nepali.models.StandardNews, on_delete=django.db.models.deletion.PROTECT, related_name='main_news', to='apps_nepali.standardnews'),
        ),
    ]
