# Generated by Django 3.2.15 on 2022-08-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0016_auto_20220825_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='standard_news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_news', to='apps_nepali.standardnews'),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='standard_news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_news', to='apps_nepali.standardnews'),
        ),
    ]
