# Generated by Django 4.0.2 on 2022-08-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0020_remove_addsubtitle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsubtitle',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_add_sub_title', to='apps_nepali.category'),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='standard_news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='main_news', to='apps_nepali.standardnews'),
        ),
    ]
