# Generated by Django 4.0.4 on 2022-06-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_english', '0002_standardnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardnews',
            name='date_time_picker',
        ),
    ]
